name: canokey_management_tool
description: CanoKey Management Tool

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  basic_utils: ^4.2.0
  cupertino_icons: ^1.0.2
  flutter_spinkit: ^5.0.0
  fluttertoast: ^8.0.9
  animate_icons: ^2.0.0
  navigation_history_observer: ^1.1.0
  intl: ^0.17.0
  logging: ^1.0.2
  shared_preferences: ^2.0.11
  flutter_web_frame: ^0.0.2
  base32: 2.1.1
  circular_countdown: ^2.1.0
  timer_controller: ^0.1.0
  cryptography: ^2.0.5
  flutter_nfc_kit:
    git:
      url: https://github.com/nfcim/flutter_nfc_kit.git
      ref: webusb_support
  
dev_dependencies:
  flutter_test:
    sdk: flutter

module:
  androidX: true

flutter:
  uses-material-design: true
  assets:
   - assets/
  fonts:
    - family: Consolas
      fonts:
        - asset: fonts/consolas/consolas.ttf

flutter_intl:
  enabled: true
